name: toyyibpay
description: >
  Flutter helper to create ToyyibPay bills, open a WebView checkout, parse the return URL,
  and optionally verify the transaction via ToyyibPay APIs for simple in-app payments.
version: 2.1.0

# Optional metadata; add real URLs when ready
# homepage: https://example.com/toyyibpay
repository: https://github.com/goutam2597/toyyibpay.git

topics:
  - payments
  - checkout
  - toyyibpay
  - malaysia

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
# If you add assets later, declare them here.
